language: node_js
node_js:
  - "6.10.0"
before_script:
  - npm install -g gulp
script: 
  - gulp
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
after_success: 
  - npm run coverage
  